# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ayush Patel
tagline: Personal Website
email: patel.ayush08@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Ayush Patel. I am an Engineer in Networks R&D Team at Samsung Electronics (South Korea).
  I am a tech enthusiast interested in Cloud Infrastructure Development, Machine Learning, 
  Networks Architecture and Development of WebApps and Mobile apps.
  I am an avid learner who is enthusiastic about learning something new each and every day. 
  On the whole, I love to code and am an enthusiastic coder.
domain: ayushpatel.com
baseurl: /jekyll/ # the subpath of your site, e.g. /blog
url: https://ayushpatel.com # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Ayush21298
github_username:  Ayush21298
author:
  name: Ayush Patel
  display_name: Ayush Patel
  picture: /images/ayush-patel-0.jpg
  email: patel.ayush08@gmail.com
  web: https://ayushpatel.com
  url: https://ayushpatel.com
  twitter: Ayush21298
  github: Ayush21298
twitter:
  username: Ayush21298
  card: summary
facebook:
  admins: ayush21298
logo: /favicon.ico
social:
  name: Ayush Patel
  links:
    - https://ayushpatel.com
    - https://github.com/Ayush21298
    - https://www.linkedin.com/in/ayush21298
    - https://www.facebook.com/ayush21298
    - https://www.instagram.com/ayush21298/
    - https://twitter.com/Ayush21298
    - https://gitlab.com/Ayush21298
google-site-verification: cuVspknwSI0oHJnOYqO1ZvifhTGfNgavgJ4nTgYEN2k
locale: en_US

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
